baseURL = 'https://fxgn.dev/'
languageCode = 'en-us'
title = 'flexagoon'

[params]
description = 'hi its me im flexagoon ğŸ…'

[markup.highlight]
style = 'algol'
noClasses = false

[markup.goldmark.renderer]
unsafe = true
